name: Bug report
description: Report a reproducible problem
body:
  - type: textarea
    id: bug
    attributes:
      label: What happened?
    validations:
      required: true
  - type: textarea
    id: repro
    attributes:
      label: Steps to reproduce
