name: Feature request
description: Suggest an improvement
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem statement
  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
